display_information:
  name: newchan
  description: Big Brother is watching you
  background_color: "#000000"
features:
  bot_user:
    display_name: newchan
    always_online: false
oauth_config:
  scopes:
    bot:
      - channels:join
      - channels:read
      - chat:write
      - users:read
settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
